### ISSUE TITLE
integrate Quilbot Api in the paraphrasing Lambda. Quillbot doesn't currently have an API but there are some open source project that provide it with some scraping I think, check link

### ISSUE THREAD

**Issue by Menwitz** [Menwitz/Autonomous-News#4]
[**Link**](https://github.com/Luen/quillbot-api)

**Comment by MELGAGIT** [comment]
Paraphrasing with QuillBot is done and currently set with headless=False.
https://github.com/MELGAGIT/Autonomous-News/commit/48c912f26d8962544340d9eebe6472a56bc6617e

TODO:

- Implement functions to configure QuillBot parameters: (language, mode, synonymsLevel).
- Bypass Cloudflare checks when headless=True.
